//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessMyMessClient.GameService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WordDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class WordDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WordIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WordKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WordId {
            get {
                return this.WordIdField;
            }
            set {
                if ((this.WordIdField.Equals(value) != true)) {
                    this.WordIdField = value;
                    this.RaisePropertyChanged("WordId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WordKey {
            get {
                return this.WordKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.WordKeyField, value) != true)) {
                    this.WordKeyField = value;
                    this.RaisePropertyChanged("WordKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class ServiceFaultDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GuessMyMessClient.GameService.ServiceErrorType ErrorTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GuessMyMessClient.GameService.ServiceErrorType ErrorType {
            get {
                return this.ErrorTypeField;
            }
            set {
                if ((this.ErrorTypeField.Equals(value) != true)) {
                    this.ErrorTypeField = value;
                    this.RaisePropertyChanged("ErrorType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Target {
            get {
                return this.TargetField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetField, value) != true)) {
                    this.TargetField = value;
                    this.RaisePropertyChanged("Target");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceErrorType", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    public enum ServiceErrorType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OperationFailed = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConnectionTimeout = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCredentials = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserAlreadyExists = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmailAlreadyRegistered = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountNotVerified = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyFull = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchNotFound = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameInProgress = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerBanned = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateRecord = 25,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DrawingDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class DrawingDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DrawingDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DrawingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsGuessedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WordKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DrawingData {
            get {
                return this.DrawingDataField;
            }
            set {
                if ((object.ReferenceEquals(this.DrawingDataField, value) != true)) {
                    this.DrawingDataField = value;
                    this.RaisePropertyChanged("DrawingData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DrawingId {
            get {
                return this.DrawingIdField;
            }
            set {
                if ((this.DrawingIdField.Equals(value) != true)) {
                    this.DrawingIdField = value;
                    this.RaisePropertyChanged("DrawingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsGuessed {
            get {
                return this.IsGuessedField;
            }
            set {
                if ((this.IsGuessedField.Equals(value) != true)) {
                    this.IsGuessedField = value;
                    this.RaisePropertyChanged("IsGuessed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerUsername {
            get {
                return this.OwnerUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerUsernameField, value) != true)) {
                    this.OwnerUsernameField = value;
                    this.RaisePropertyChanged("OwnerUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WordKey {
            get {
                return this.WordKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.WordKeyField, value) != true)) {
                    this.WordKeyField = value;
                    this.RaisePropertyChanged("WordKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuessDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class GuessDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DrawingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuessTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuesserUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCorrectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WordKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DrawingId {
            get {
                return this.DrawingIdField;
            }
            set {
                if ((this.DrawingIdField.Equals(value) != true)) {
                    this.DrawingIdField = value;
                    this.RaisePropertyChanged("DrawingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GuessText {
            get {
                return this.GuessTextField;
            }
            set {
                if ((object.ReferenceEquals(this.GuessTextField, value) != true)) {
                    this.GuessTextField = value;
                    this.RaisePropertyChanged("GuessText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GuesserUsername {
            get {
                return this.GuesserUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.GuesserUsernameField, value) != true)) {
                    this.GuesserUsernameField = value;
                    this.RaisePropertyChanged("GuesserUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCorrect {
            get {
                return this.IsCorrectField;
            }
            set {
                if ((this.IsCorrectField.Equals(value) != true)) {
                    this.IsCorrectField = value;
                    this.RaisePropertyChanged("IsCorrect");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WordKey {
            get {
                return this.WordKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.WordKeyField, value) != true)) {
                    this.WordKeyField = value;
                    this.RaisePropertyChanged("WordKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerScoreDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class PlayerScoreDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Rank {
            get {
                return this.RankField;
            }
            set {
                if ((this.RankField.Equals(value) != true)) {
                    this.RankField = value;
                    this.RaisePropertyChanged("Rank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameService.IGameService", CallbackContract=typeof(GuessMyMessClient.GameService.IGameServiceCallback))]
    public interface IGameService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/Connect")]
        void Connect(string username, string matchId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/Connect")]
        System.Threading.Tasks.Task ConnectAsync(string username, string matchId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/Disconnect")]
        void Disconnect(string username, string matchId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/Disconnect")]
        System.Threading.Tasks.Task DisconnectAsync(string username, string matchId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/SelectWord")]
        void SelectWord(string username, string matchId, string selectedWord);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/SelectWord")]
        System.Threading.Tasks.Task SelectWordAsync(string username, string matchId, string selectedWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/GetRandomWords", ReplyAction="http://tempuri.org/IGameService/GetRandomWordsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessMyMessClient.GameService.ServiceFaultDto), Action="http://tempuri.org/IGameService/GetRandomWordsServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
            "")]
        GuessMyMessClient.GameService.WordDto[] GetRandomWords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/GetRandomWords", ReplyAction="http://tempuri.org/IGameService/GetRandomWordsResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.GameService.WordDto[]> GetRandomWordsAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/SubmitDrawing")]
        void SubmitDrawing(string username, string matchId, byte[] drawingData);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/SubmitDrawing")]
        System.Threading.Tasks.Task SubmitDrawingAsync(string username, string matchId, byte[] drawingData);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/SubmitGuess")]
        void SubmitGuess(string username, string matchId, int drawingId, string guess);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/SubmitGuess")]
        System.Threading.Tasks.Task SubmitGuessAsync(string username, string matchId, int drawingId, string guess);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/SendInGameChatMessage")]
        void SendInGameChatMessage(string username, string matchId, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/SendInGameChatMessage")]
        System.Threading.Tasks.Task SendInGameChatMessageAsync(string username, string matchId, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/StartGame")]
        void StartGame(string matchId, int totalRounds, string[] playerUsernames);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/StartGame")]
        System.Threading.Tasks.Task StartGameAsync(string matchId, int totalRounds, string[] playerUsernames);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/OnRoundStart")]
        void OnRoundStart(int roundNumber, string[] wordOptions);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/OnDrawingPhaseStart")]
        void OnDrawingPhaseStart(int durationSeconds);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/OnGuessingPhaseStart")]
        void OnGuessingPhaseStart(GuessMyMessClient.GameService.DrawingDto drawing);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/OnInGameMessageReceived")]
        void OnInGameMessageReceived(string sender, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/OnAnswersPhaseStart")]
        void OnAnswersPhaseStart(GuessMyMessClient.GameService.DrawingDto[] allDrawings, GuessMyMessClient.GameService.GuessDto[] allGuesses, GuessMyMessClient.GameService.PlayerScoreDto[] currentScores);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/OnShowNextDrawing")]
        void OnShowNextDrawing(GuessMyMessClient.GameService.DrawingDto nextDrawing);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/OnGameEnd")]
        void OnGameEnd(GuessMyMessClient.GameService.PlayerScoreDto[] finalScores);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameServiceChannel : GuessMyMessClient.GameService.IGameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameServiceClient : System.ServiceModel.DuplexClientBase<GuessMyMessClient.GameService.IGameService>, GuessMyMessClient.GameService.IGameService {
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Connect(string username, string matchId) {
            base.Channel.Connect(username, matchId);
        }
        
        public System.Threading.Tasks.Task ConnectAsync(string username, string matchId) {
            return base.Channel.ConnectAsync(username, matchId);
        }
        
        public void Disconnect(string username, string matchId) {
            base.Channel.Disconnect(username, matchId);
        }
        
        public System.Threading.Tasks.Task DisconnectAsync(string username, string matchId) {
            return base.Channel.DisconnectAsync(username, matchId);
        }
        
        public void SelectWord(string username, string matchId, string selectedWord) {
            base.Channel.SelectWord(username, matchId, selectedWord);
        }
        
        public System.Threading.Tasks.Task SelectWordAsync(string username, string matchId, string selectedWord) {
            return base.Channel.SelectWordAsync(username, matchId, selectedWord);
        }
        
        public GuessMyMessClient.GameService.WordDto[] GetRandomWords() {
            return base.Channel.GetRandomWords();
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.GameService.WordDto[]> GetRandomWordsAsync() {
            return base.Channel.GetRandomWordsAsync();
        }
        
        public void SubmitDrawing(string username, string matchId, byte[] drawingData) {
            base.Channel.SubmitDrawing(username, matchId, drawingData);
        }
        
        public System.Threading.Tasks.Task SubmitDrawingAsync(string username, string matchId, byte[] drawingData) {
            return base.Channel.SubmitDrawingAsync(username, matchId, drawingData);
        }
        
        public void SubmitGuess(string username, string matchId, int drawingId, string guess) {
            base.Channel.SubmitGuess(username, matchId, drawingId, guess);
        }
        
        public System.Threading.Tasks.Task SubmitGuessAsync(string username, string matchId, int drawingId, string guess) {
            return base.Channel.SubmitGuessAsync(username, matchId, drawingId, guess);
        }
        
        public void SendInGameChatMessage(string username, string matchId, string message) {
            base.Channel.SendInGameChatMessage(username, matchId, message);
        }
        
        public System.Threading.Tasks.Task SendInGameChatMessageAsync(string username, string matchId, string message) {
            return base.Channel.SendInGameChatMessageAsync(username, matchId, message);
        }
        
        public void StartGame(string matchId, int totalRounds, string[] playerUsernames) {
            base.Channel.StartGame(matchId, totalRounds, playerUsernames);
        }
        
        public System.Threading.Tasks.Task StartGameAsync(string matchId, int totalRounds, string[] playerUsernames) {
            return base.Channel.StartGameAsync(matchId, totalRounds, playerUsernames);
        }
    }
}
