//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessMyMessClient.ProfileService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserProfileDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class UserProfileDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvatarIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GenderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GuessMyMessClient.ProfileService.SocialNetworkDto[] socialNetworksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvatarId {
            get {
                return this.AvatarIdField;
            }
            set {
                if ((this.AvatarIdField.Equals(value) != true)) {
                    this.AvatarIdField = value;
                    this.RaisePropertyChanged("AvatarId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GenderId {
            get {
                return this.GenderIdField;
            }
            set {
                if ((this.GenderIdField.Equals(value) != true)) {
                    this.GenderIdField = value;
                    this.RaisePropertyChanged("GenderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GuessMyMessClient.ProfileService.SocialNetworkDto[] socialNetworks {
            get {
                return this.socialNetworksField;
            }
            set {
                if ((object.ReferenceEquals(this.socialNetworksField, value) != true)) {
                    this.socialNetworksField = value;
                    this.RaisePropertyChanged("socialNetworks");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SocialNetworkDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class SocialNetworkDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NetworkTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserLinkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NetworkType {
            get {
                return this.NetworkTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.NetworkTypeField, value) != true)) {
                    this.NetworkTypeField = value;
                    this.RaisePropertyChanged("NetworkType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserLink {
            get {
                return this.UserLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.UserLinkField, value) != true)) {
                    this.UserLinkField = value;
                    this.RaisePropertyChanged("UserLink");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class ServiceFaultDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GuessMyMessClient.ProfileService.ServiceErrorType ErrorTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GuessMyMessClient.ProfileService.ServiceErrorType ErrorType {
            get {
                return this.ErrorTypeField;
            }
            set {
                if ((this.ErrorTypeField.Equals(value) != true)) {
                    this.ErrorTypeField = value;
                    this.RaisePropertyChanged("ErrorType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Target {
            get {
                return this.TargetField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetField, value) != true)) {
                    this.TargetField = value;
                    this.RaisePropertyChanged("Target");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceErrorType", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    public enum ServiceErrorType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OperationFailed = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConnectionTimeout = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCredentials = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserAlreadyExists = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmailAlreadyRegistered = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountNotVerified = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyFull = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchNotFound = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameInProgress = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerBanned = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateRecord = 25,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class OperationResultDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvatarDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class AvatarDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] AvatarDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvatarNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAvatarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] AvatarData {
            get {
                return this.AvatarDataField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarDataField, value) != true)) {
                    this.AvatarDataField = value;
                    this.RaisePropertyChanged("AvatarData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvatarName {
            get {
                return this.AvatarNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarNameField, value) != true)) {
                    this.AvatarNameField = value;
                    this.RaisePropertyChanged("AvatarName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAvatar {
            get {
                return this.IdAvatarField;
            }
            set {
                if ((this.IdAvatarField.Equals(value) != true)) {
                    this.IdAvatarField = value;
                    this.RaisePropertyChanged("IdAvatar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProfileService.IUserProfileService")]
    public interface IUserProfileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/GetUserProfile", ReplyAction="http://tempuri.org/IUserProfileService/GetUserProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessMyMessClient.ProfileService.ServiceFaultDto), Action="http://tempuri.org/IUserProfileService/GetUserProfileServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
            "")]
        GuessMyMessClient.ProfileService.UserProfileDto GetUserProfile(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/GetUserProfile", ReplyAction="http://tempuri.org/IUserProfileService/GetUserProfileResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.UserProfileDto> GetUserProfileAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/UpdateProfile", ReplyAction="http://tempuri.org/IUserProfileService/UpdateProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessMyMessClient.ProfileService.ServiceFaultDto), Action="http://tempuri.org/IUserProfileService/UpdateProfileServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
            "")]
        GuessMyMessClient.ProfileService.OperationResultDto UpdateProfile(string username, GuessMyMessClient.ProfileService.UserProfileDto profileData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/UpdateProfile", ReplyAction="http://tempuri.org/IUserProfileService/UpdateProfileResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.OperationResultDto> UpdateProfileAsync(string username, GuessMyMessClient.ProfileService.UserProfileDto profileData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/AddOrUpdateSocialNetwork", ReplyAction="http://tempuri.org/IUserProfileService/AddOrUpdateSocialNetworkResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessMyMessClient.ProfileService.ServiceFaultDto), Action="http://tempuri.org/IUserProfileService/AddOrUpdateSocialNetworkServiceFaultDtoFau" +
            "lt", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
            "")]
        GuessMyMessClient.ProfileService.OperationResultDto AddOrUpdateSocialNetwork(string username, GuessMyMessClient.ProfileService.SocialNetworkDto socialNetwork);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/AddOrUpdateSocialNetwork", ReplyAction="http://tempuri.org/IUserProfileService/AddOrUpdateSocialNetworkResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.OperationResultDto> AddOrUpdateSocialNetworkAsync(string username, GuessMyMessClient.ProfileService.SocialNetworkDto socialNetwork);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/RequestChangeEmail", ReplyAction="http://tempuri.org/IUserProfileService/RequestChangeEmailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessMyMessClient.ProfileService.ServiceFaultDto), Action="http://tempuri.org/IUserProfileService/RequestChangeEmailServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
            "")]
        GuessMyMessClient.ProfileService.OperationResultDto RequestChangeEmail(string username, string newEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/RequestChangeEmail", ReplyAction="http://tempuri.org/IUserProfileService/RequestChangeEmailResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.OperationResultDto> RequestChangeEmailAsync(string username, string newEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/ConfirmChangeEmail", ReplyAction="http://tempuri.org/IUserProfileService/ConfirmChangeEmailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessMyMessClient.ProfileService.ServiceFaultDto), Action="http://tempuri.org/IUserProfileService/ConfirmChangeEmailServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
            "")]
        GuessMyMessClient.ProfileService.OperationResultDto ConfirmChangeEmail(string username, string verificationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/ConfirmChangeEmail", ReplyAction="http://tempuri.org/IUserProfileService/ConfirmChangeEmailResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.OperationResultDto> ConfirmChangeEmailAsync(string username, string verificationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/RequestChangePassword", ReplyAction="http://tempuri.org/IUserProfileService/RequestChangePasswordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessMyMessClient.ProfileService.ServiceFaultDto), Action="http://tempuri.org/IUserProfileService/RequestChangePasswordServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
            "")]
        GuessMyMessClient.ProfileService.OperationResultDto RequestChangePassword(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/RequestChangePassword", ReplyAction="http://tempuri.org/IUserProfileService/RequestChangePasswordResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.OperationResultDto> RequestChangePasswordAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/ConfirmChangePassword", ReplyAction="http://tempuri.org/IUserProfileService/ConfirmChangePasswordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessMyMessClient.ProfileService.ServiceFaultDto), Action="http://tempuri.org/IUserProfileService/ConfirmChangePasswordServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
            "")]
        GuessMyMessClient.ProfileService.OperationResultDto ConfirmChangePassword(string username, string newPassword, string verificationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/ConfirmChangePassword", ReplyAction="http://tempuri.org/IUserProfileService/ConfirmChangePasswordResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.OperationResultDto> ConfirmChangePasswordAsync(string username, string newPassword, string verificationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/GetAvailableAvatars", ReplyAction="http://tempuri.org/IUserProfileService/GetAvailableAvatarsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessMyMessClient.ProfileService.ServiceFaultDto), Action="http://tempuri.org/IUserProfileService/GetAvailableAvatarsServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
            "")]
        GuessMyMessClient.ProfileService.AvatarDto[] GetAvailableAvatars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/GetAvailableAvatars", ReplyAction="http://tempuri.org/IUserProfileService/GetAvailableAvatarsResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.AvatarDto[]> GetAvailableAvatarsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserProfileServiceChannel : GuessMyMessClient.ProfileService.IUserProfileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserProfileServiceClient : System.ServiceModel.ClientBase<GuessMyMessClient.ProfileService.IUserProfileService>, GuessMyMessClient.ProfileService.IUserProfileService {
        
        public UserProfileServiceClient() {
        }
        
        public UserProfileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserProfileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserProfileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserProfileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GuessMyMessClient.ProfileService.UserProfileDto GetUserProfile(string username) {
            return base.Channel.GetUserProfile(username);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.UserProfileDto> GetUserProfileAsync(string username) {
            return base.Channel.GetUserProfileAsync(username);
        }
        
        public GuessMyMessClient.ProfileService.OperationResultDto UpdateProfile(string username, GuessMyMessClient.ProfileService.UserProfileDto profileData) {
            return base.Channel.UpdateProfile(username, profileData);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.OperationResultDto> UpdateProfileAsync(string username, GuessMyMessClient.ProfileService.UserProfileDto profileData) {
            return base.Channel.UpdateProfileAsync(username, profileData);
        }
        
        public GuessMyMessClient.ProfileService.OperationResultDto AddOrUpdateSocialNetwork(string username, GuessMyMessClient.ProfileService.SocialNetworkDto socialNetwork) {
            return base.Channel.AddOrUpdateSocialNetwork(username, socialNetwork);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.OperationResultDto> AddOrUpdateSocialNetworkAsync(string username, GuessMyMessClient.ProfileService.SocialNetworkDto socialNetwork) {
            return base.Channel.AddOrUpdateSocialNetworkAsync(username, socialNetwork);
        }
        
        public GuessMyMessClient.ProfileService.OperationResultDto RequestChangeEmail(string username, string newEmail) {
            return base.Channel.RequestChangeEmail(username, newEmail);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.OperationResultDto> RequestChangeEmailAsync(string username, string newEmail) {
            return base.Channel.RequestChangeEmailAsync(username, newEmail);
        }
        
        public GuessMyMessClient.ProfileService.OperationResultDto ConfirmChangeEmail(string username, string verificationCode) {
            return base.Channel.ConfirmChangeEmail(username, verificationCode);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.OperationResultDto> ConfirmChangeEmailAsync(string username, string verificationCode) {
            return base.Channel.ConfirmChangeEmailAsync(username, verificationCode);
        }
        
        public GuessMyMessClient.ProfileService.OperationResultDto RequestChangePassword(string username) {
            return base.Channel.RequestChangePassword(username);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.OperationResultDto> RequestChangePasswordAsync(string username) {
            return base.Channel.RequestChangePasswordAsync(username);
        }
        
        public GuessMyMessClient.ProfileService.OperationResultDto ConfirmChangePassword(string username, string newPassword, string verificationCode) {
            return base.Channel.ConfirmChangePassword(username, newPassword, verificationCode);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.OperationResultDto> ConfirmChangePasswordAsync(string username, string newPassword, string verificationCode) {
            return base.Channel.ConfirmChangePasswordAsync(username, newPassword, verificationCode);
        }
        
        public GuessMyMessClient.ProfileService.AvatarDto[] GetAvailableAvatars() {
            return base.Channel.GetAvailableAvatars();
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.AvatarDto[]> GetAvailableAvatarsAsync() {
            return base.Channel.GetAvailableAvatarsAsync();
        }
    }
}
