//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessMyMessClient.ProfileService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserProfileDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class UserProfileDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int avatarIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int genderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GuessMyMessClient.ProfileService.SocialNetworkDto[] socialNetworksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int avatarId {
            get {
                return this.avatarIdField;
            }
            set {
                if ((this.avatarIdField.Equals(value) != true)) {
                    this.avatarIdField = value;
                    this.RaisePropertyChanged("avatarId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                if ((this.dateOfBirthField.Equals(value) != true)) {
                    this.dateOfBirthField = value;
                    this.RaisePropertyChanged("dateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int genderId {
            get {
                return this.genderIdField;
            }
            set {
                if ((this.genderIdField.Equals(value) != true)) {
                    this.genderIdField = value;
                    this.RaisePropertyChanged("genderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GuessMyMessClient.ProfileService.SocialNetworkDto[] socialNetworks {
            get {
                return this.socialNetworksField;
            }
            set {
                if ((object.ReferenceEquals(this.socialNetworksField, value) != true)) {
                    this.socialNetworksField = value;
                    this.RaisePropertyChanged("socialNetworks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SocialNetworkDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class SocialNetworkDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string networkTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userLinkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string networkType {
            get {
                return this.networkTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.networkTypeField, value) != true)) {
                    this.networkTypeField = value;
                    this.RaisePropertyChanged("networkType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userLink {
            get {
                return this.userLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.userLinkField, value) != true)) {
                    this.userLinkField = value;
                    this.RaisePropertyChanged("userLink");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class OperationResultDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvatarDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class AvatarDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] avatarDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string avatarNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idAvatarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] avatarData {
            get {
                return this.avatarDataField;
            }
            set {
                if ((object.ReferenceEquals(this.avatarDataField, value) != true)) {
                    this.avatarDataField = value;
                    this.RaisePropertyChanged("avatarData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string avatarName {
            get {
                return this.avatarNameField;
            }
            set {
                if ((object.ReferenceEquals(this.avatarNameField, value) != true)) {
                    this.avatarNameField = value;
                    this.RaisePropertyChanged("avatarName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAvatar {
            get {
                return this.idAvatarField;
            }
            set {
                if ((this.idAvatarField.Equals(value) != true)) {
                    this.idAvatarField = value;
                    this.RaisePropertyChanged("idAvatar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProfileService.IUserProfileService")]
    public interface IUserProfileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/GetUserProfile", ReplyAction="http://tempuri.org/IUserProfileService/GetUserProfileResponse")]
        GuessMyMessClient.ProfileService.UserProfileDto GetUserProfile(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/GetUserProfile", ReplyAction="http://tempuri.org/IUserProfileService/GetUserProfileResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.UserProfileDto> GetUserProfileAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/UpdateProfile", ReplyAction="http://tempuri.org/IUserProfileService/UpdateProfileResponse")]
        GuessMyMessClient.ProfileService.OperationResultDto UpdateProfile(string username, GuessMyMessClient.ProfileService.UserProfileDto profileData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/UpdateProfile", ReplyAction="http://tempuri.org/IUserProfileService/UpdateProfileResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.OperationResultDto> UpdateProfileAsync(string username, GuessMyMessClient.ProfileService.UserProfileDto profileData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/RequestChangeEmail", ReplyAction="http://tempuri.org/IUserProfileService/RequestChangeEmailResponse")]
        GuessMyMessClient.ProfileService.OperationResultDto RequestChangeEmail(string username, string newEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/RequestChangeEmail", ReplyAction="http://tempuri.org/IUserProfileService/RequestChangeEmailResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.OperationResultDto> RequestChangeEmailAsync(string username, string newEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/ConfirmChangeEmail", ReplyAction="http://tempuri.org/IUserProfileService/ConfirmChangeEmailResponse")]
        GuessMyMessClient.ProfileService.OperationResultDto ConfirmChangeEmail(string username, string verificationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/ConfirmChangeEmail", ReplyAction="http://tempuri.org/IUserProfileService/ConfirmChangeEmailResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.OperationResultDto> ConfirmChangeEmailAsync(string username, string verificationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/RequestChangePassword", ReplyAction="http://tempuri.org/IUserProfileService/RequestChangePasswordResponse")]
        GuessMyMessClient.ProfileService.OperationResultDto RequestChangePassword(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/RequestChangePassword", ReplyAction="http://tempuri.org/IUserProfileService/RequestChangePasswordResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.OperationResultDto> RequestChangePasswordAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/ConfirmChangePassword", ReplyAction="http://tempuri.org/IUserProfileService/ConfirmChangePasswordResponse")]
        GuessMyMessClient.ProfileService.OperationResultDto ConfirmChangePassword(string username, string newPassword, string verificationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/ConfirmChangePassword", ReplyAction="http://tempuri.org/IUserProfileService/ConfirmChangePasswordResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.OperationResultDto> ConfirmChangePasswordAsync(string username, string newPassword, string verificationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/GetAvailableAvatars", ReplyAction="http://tempuri.org/IUserProfileService/GetAvailableAvatarsResponse")]
        GuessMyMessClient.ProfileService.AvatarDto[] GetAvailableAvatars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/GetAvailableAvatars", ReplyAction="http://tempuri.org/IUserProfileService/GetAvailableAvatarsResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.AvatarDto[]> GetAvailableAvatarsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserProfileServiceChannel : GuessMyMessClient.ProfileService.IUserProfileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserProfileServiceClient : System.ServiceModel.ClientBase<GuessMyMessClient.ProfileService.IUserProfileService>, GuessMyMessClient.ProfileService.IUserProfileService {
        
        public UserProfileServiceClient() {
        }
        
        public UserProfileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserProfileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserProfileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserProfileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GuessMyMessClient.ProfileService.UserProfileDto GetUserProfile(string username) {
            return base.Channel.GetUserProfile(username);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.UserProfileDto> GetUserProfileAsync(string username) {
            return base.Channel.GetUserProfileAsync(username);
        }
        
        public GuessMyMessClient.ProfileService.OperationResultDto UpdateProfile(string username, GuessMyMessClient.ProfileService.UserProfileDto profileData) {
            return base.Channel.UpdateProfile(username, profileData);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.OperationResultDto> UpdateProfileAsync(string username, GuessMyMessClient.ProfileService.UserProfileDto profileData) {
            return base.Channel.UpdateProfileAsync(username, profileData);
        }
        
        public GuessMyMessClient.ProfileService.OperationResultDto RequestChangeEmail(string username, string newEmail) {
            return base.Channel.RequestChangeEmail(username, newEmail);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.OperationResultDto> RequestChangeEmailAsync(string username, string newEmail) {
            return base.Channel.RequestChangeEmailAsync(username, newEmail);
        }
        
        public GuessMyMessClient.ProfileService.OperationResultDto ConfirmChangeEmail(string username, string verificationCode) {
            return base.Channel.ConfirmChangeEmail(username, verificationCode);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.OperationResultDto> ConfirmChangeEmailAsync(string username, string verificationCode) {
            return base.Channel.ConfirmChangeEmailAsync(username, verificationCode);
        }
        
        public GuessMyMessClient.ProfileService.OperationResultDto RequestChangePassword(string username) {
            return base.Channel.RequestChangePassword(username);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.OperationResultDto> RequestChangePasswordAsync(string username) {
            return base.Channel.RequestChangePasswordAsync(username);
        }
        
        public GuessMyMessClient.ProfileService.OperationResultDto ConfirmChangePassword(string username, string newPassword, string verificationCode) {
            return base.Channel.ConfirmChangePassword(username, newPassword, verificationCode);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.OperationResultDto> ConfirmChangePasswordAsync(string username, string newPassword, string verificationCode) {
            return base.Channel.ConfirmChangePasswordAsync(username, newPassword, verificationCode);
        }
        
        public GuessMyMessClient.ProfileService.AvatarDto[] GetAvailableAvatars() {
            return base.Channel.GetAvailableAvatars();
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.ProfileService.AvatarDto[]> GetAvailableAvatarsAsync() {
            return base.Channel.GetAvailableAvatarsAsync();
        }
    }
}
