//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessMyMessClient.SocialService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class FriendDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isOnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isOnline {
            get {
                return this.isOnlineField;
            }
            set {
                if ((this.isOnlineField.Equals(value) != true)) {
                    this.isOnlineField = value;
                    this.RaisePropertyChanged("isOnline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendRequestInfoDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class FriendRequestInfoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime requestDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string requesterUsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime requestDate {
            get {
                return this.requestDateField;
            }
            set {
                if ((this.requestDateField.Equals(value) != true)) {
                    this.requestDateField = value;
                    this.RaisePropertyChanged("requestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string requesterUsername {
            get {
                return this.requesterUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.requesterUsernameField, value) != true)) {
                    this.requesterUsernameField = value;
                    this.RaisePropertyChanged("requesterUsername");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserProfileDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class UserProfileDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvatarIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GenderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GuessMyMessClient.SocialService.SocialNetworkDto[] socialNetworksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvatarId {
            get {
                return this.AvatarIdField;
            }
            set {
                if ((this.AvatarIdField.Equals(value) != true)) {
                    this.AvatarIdField = value;
                    this.RaisePropertyChanged("AvatarId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GenderId {
            get {
                return this.GenderIdField;
            }
            set {
                if ((this.GenderIdField.Equals(value) != true)) {
                    this.GenderIdField = value;
                    this.RaisePropertyChanged("GenderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GuessMyMessClient.SocialService.SocialNetworkDto[] socialNetworks {
            get {
                return this.socialNetworksField;
            }
            set {
                if ((object.ReferenceEquals(this.socialNetworksField, value) != true)) {
                    this.socialNetworksField = value;
                    this.RaisePropertyChanged("socialNetworks");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SocialNetworkDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class SocialNetworkDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string networkTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userLinkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string networkType {
            get {
                return this.networkTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.networkTypeField, value) != true)) {
                    this.networkTypeField = value;
                    this.RaisePropertyChanged("networkType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userLink {
            get {
                return this.userLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.userLinkField, value) != true)) {
                    this.userLinkField = value;
                    this.RaisePropertyChanged("userLink");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class OperationResultDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DirectMessageDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class DirectMessageDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string recipientUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string senderUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime timestampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string content {
            get {
                return this.contentField;
            }
            set {
                if ((object.ReferenceEquals(this.contentField, value) != true)) {
                    this.contentField = value;
                    this.RaisePropertyChanged("content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string recipientUsername {
            get {
                return this.recipientUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.recipientUsernameField, value) != true)) {
                    this.recipientUsernameField = value;
                    this.RaisePropertyChanged("recipientUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string senderUsername {
            get {
                return this.senderUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.senderUsernameField, value) != true)) {
                    this.senderUsernameField = value;
                    this.RaisePropertyChanged("senderUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                if ((this.timestampField.Equals(value) != true)) {
                    this.timestampField = value;
                    this.RaisePropertyChanged("timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SocialService.ISocialService", CallbackContract=typeof(GuessMyMessClient.SocialService.ISocialServiceCallback))]
    public interface ISocialService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialService/getFriendsList", ReplyAction="http://tempuri.org/ISocialService/getFriendsListResponse")]
        GuessMyMessClient.SocialService.FriendDto[] getFriendsList(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialService/getFriendsList", ReplyAction="http://tempuri.org/ISocialService/getFriendsListResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.SocialService.FriendDto[]> getFriendsListAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialService/getFriendRequests", ReplyAction="http://tempuri.org/ISocialService/getFriendRequestsResponse")]
        GuessMyMessClient.SocialService.FriendRequestInfoDto[] getFriendRequests(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialService/getFriendRequests", ReplyAction="http://tempuri.org/ISocialService/getFriendRequestsResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.SocialService.FriendRequestInfoDto[]> getFriendRequestsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialService/searchUsers", ReplyAction="http://tempuri.org/ISocialService/searchUsersResponse")]
        GuessMyMessClient.SocialService.UserProfileDto[] searchUsers(string searchUsername, string requesterUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialService/searchUsers", ReplyAction="http://tempuri.org/ISocialService/searchUsersResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.SocialService.UserProfileDto[]> searchUsersAsync(string searchUsername, string requesterUsername);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/sendFriendRequest")]
        void sendFriendRequest(string requesterUsername, string targetUsername);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/sendFriendRequest")]
        System.Threading.Tasks.Task sendFriendRequestAsync(string requesterUsername, string targetUsername);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/respondToFriendRequest")]
        void respondToFriendRequest(string targetUsername, string requesterUsername, bool accepted);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/respondToFriendRequest")]
        System.Threading.Tasks.Task respondToFriendRequestAsync(string targetUsername, string requesterUsername, bool accepted);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/removeFriend")]
        void removeFriend(string username, string friendToRemove);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/removeFriend")]
        System.Threading.Tasks.Task removeFriendAsync(string username, string friendToRemove);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialService/inviteFriendToGameByEmail", ReplyAction="http://tempuri.org/ISocialService/inviteFriendToGameByEmailResponse")]
        GuessMyMessClient.SocialService.OperationResultDto inviteFriendToGameByEmail(string fromUsername, string friendEmail, string matchCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialService/inviteFriendToGameByEmail", ReplyAction="http://tempuri.org/ISocialService/inviteFriendToGameByEmailResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.SocialService.OperationResultDto> inviteFriendToGameByEmailAsync(string fromUsername, string friendEmail, string matchCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/SendDirectMessage")]
        void SendDirectMessage(GuessMyMessClient.SocialService.DirectMessageDto message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/SendDirectMessage")]
        System.Threading.Tasks.Task SendDirectMessageAsync(GuessMyMessClient.SocialService.DirectMessageDto message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialService/GetConversations", ReplyAction="http://tempuri.org/ISocialService/GetConversationsResponse")]
        GuessMyMessClient.SocialService.FriendDto[] GetConversations(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialService/GetConversations", ReplyAction="http://tempuri.org/ISocialService/GetConversationsResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.SocialService.FriendDto[]> GetConversationsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialService/GetConversationHistory", ReplyAction="http://tempuri.org/ISocialService/GetConversationHistoryResponse")]
        GuessMyMessClient.SocialService.DirectMessageDto[] GetConversationHistory(string user1, string user2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialService/GetConversationHistory", ReplyAction="http://tempuri.org/ISocialService/GetConversationHistoryResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.SocialService.DirectMessageDto[]> GetConversationHistoryAsync(string user1, string user2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISocialServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/notifyFriendRequest")]
        void notifyFriendRequest(string fromUsername);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/notifyFriendResponse")]
        void notifyFriendResponse(string fromUsername, bool accepted);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/notifyFriendStatusChanged")]
        void notifyFriendStatusChanged(string friendUsername, bool isOnline);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/NotifyMessageReceived")]
        void NotifyMessageReceived(GuessMyMessClient.SocialService.DirectMessageDto message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISocialServiceChannel : GuessMyMessClient.SocialService.ISocialService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SocialServiceClient : System.ServiceModel.DuplexClientBase<GuessMyMessClient.SocialService.ISocialService>, GuessMyMessClient.SocialService.ISocialService {
        
        public SocialServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public SocialServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public SocialServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SocialServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SocialServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public GuessMyMessClient.SocialService.FriendDto[] getFriendsList(string username) {
            return base.Channel.getFriendsList(username);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.SocialService.FriendDto[]> getFriendsListAsync(string username) {
            return base.Channel.getFriendsListAsync(username);
        }
        
        public GuessMyMessClient.SocialService.FriendRequestInfoDto[] getFriendRequests(string username) {
            return base.Channel.getFriendRequests(username);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.SocialService.FriendRequestInfoDto[]> getFriendRequestsAsync(string username) {
            return base.Channel.getFriendRequestsAsync(username);
        }
        
        public GuessMyMessClient.SocialService.UserProfileDto[] searchUsers(string searchUsername, string requesterUsername) {
            return base.Channel.searchUsers(searchUsername, requesterUsername);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.SocialService.UserProfileDto[]> searchUsersAsync(string searchUsername, string requesterUsername) {
            return base.Channel.searchUsersAsync(searchUsername, requesterUsername);
        }
        
        public void sendFriendRequest(string requesterUsername, string targetUsername) {
            base.Channel.sendFriendRequest(requesterUsername, targetUsername);
        }
        
        public System.Threading.Tasks.Task sendFriendRequestAsync(string requesterUsername, string targetUsername) {
            return base.Channel.sendFriendRequestAsync(requesterUsername, targetUsername);
        }
        
        public void respondToFriendRequest(string targetUsername, string requesterUsername, bool accepted) {
            base.Channel.respondToFriendRequest(targetUsername, requesterUsername, accepted);
        }
        
        public System.Threading.Tasks.Task respondToFriendRequestAsync(string targetUsername, string requesterUsername, bool accepted) {
            return base.Channel.respondToFriendRequestAsync(targetUsername, requesterUsername, accepted);
        }
        
        public void removeFriend(string username, string friendToRemove) {
            base.Channel.removeFriend(username, friendToRemove);
        }
        
        public System.Threading.Tasks.Task removeFriendAsync(string username, string friendToRemove) {
            return base.Channel.removeFriendAsync(username, friendToRemove);
        }
        
        public GuessMyMessClient.SocialService.OperationResultDto inviteFriendToGameByEmail(string fromUsername, string friendEmail, string matchCode) {
            return base.Channel.inviteFriendToGameByEmail(fromUsername, friendEmail, matchCode);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.SocialService.OperationResultDto> inviteFriendToGameByEmailAsync(string fromUsername, string friendEmail, string matchCode) {
            return base.Channel.inviteFriendToGameByEmailAsync(fromUsername, friendEmail, matchCode);
        }
        
        public void SendDirectMessage(GuessMyMessClient.SocialService.DirectMessageDto message) {
            base.Channel.SendDirectMessage(message);
        }
        
        public System.Threading.Tasks.Task SendDirectMessageAsync(GuessMyMessClient.SocialService.DirectMessageDto message) {
            return base.Channel.SendDirectMessageAsync(message);
        }
        
        public GuessMyMessClient.SocialService.FriendDto[] GetConversations(string username) {
            return base.Channel.GetConversations(username);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.SocialService.FriendDto[]> GetConversationsAsync(string username) {
            return base.Channel.GetConversationsAsync(username);
        }
        
        public GuessMyMessClient.SocialService.DirectMessageDto[] GetConversationHistory(string user1, string user2) {
            return base.Channel.GetConversationHistory(user1, user2);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.SocialService.DirectMessageDto[]> GetConversationHistoryAsync(string user1, string user2) {
            return base.Channel.GetConversationHistoryAsync(user1, user2);
        }
    }
}
