//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessMyMessClient.SocialService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class FriendDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isOnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isOnline {
            get {
                return this.isOnlineField;
            }
            set {
                if ((this.isOnlineField.Equals(value) != true)) {
                    this.isOnlineField = value;
                    this.RaisePropertyChanged("isOnline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendRequestInfoDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class FriendRequestInfoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime requestDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string requesterUsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime requestDate {
            get {
                return this.requestDateField;
            }
            set {
                if ((this.requestDateField.Equals(value) != true)) {
                    this.requestDateField = value;
                    this.RaisePropertyChanged("requestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string requesterUsername {
            get {
                return this.requesterUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.requesterUsernameField, value) != true)) {
                    this.requesterUsernameField = value;
                    this.RaisePropertyChanged("requesterUsername");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserProfileDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class UserProfileDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvatarIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GenderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GuessMyMessClient.SocialService.SocialNetworkDto[] socialNetworksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvatarId {
            get {
                return this.AvatarIdField;
            }
            set {
                if ((this.AvatarIdField.Equals(value) != true)) {
                    this.AvatarIdField = value;
                    this.RaisePropertyChanged("AvatarId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GenderId {
            get {
                return this.GenderIdField;
            }
            set {
                if ((this.GenderIdField.Equals(value) != true)) {
                    this.GenderIdField = value;
                    this.RaisePropertyChanged("GenderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GuessMyMessClient.SocialService.SocialNetworkDto[] socialNetworks {
            get {
                return this.socialNetworksField;
            }
            set {
                if ((object.ReferenceEquals(this.socialNetworksField, value) != true)) {
                    this.socialNetworksField = value;
                    this.RaisePropertyChanged("socialNetworks");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SocialNetworkDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class SocialNetworkDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string networkTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userLinkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string networkType {
            get {
                return this.networkTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.networkTypeField, value) != true)) {
                    this.networkTypeField = value;
                    this.RaisePropertyChanged("networkType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userLink {
            get {
                return this.userLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.userLinkField, value) != true)) {
                    this.userLinkField = value;
                    this.RaisePropertyChanged("userLink");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class OperationResultDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DirectMessageDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class DirectMessageDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string recipientUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string senderUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime timestampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string content {
            get {
                return this.contentField;
            }
            set {
                if ((object.ReferenceEquals(this.contentField, value) != true)) {
                    this.contentField = value;
                    this.RaisePropertyChanged("content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string recipientUsername {
            get {
                return this.recipientUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.recipientUsernameField, value) != true)) {
                    this.recipientUsernameField = value;
                    this.RaisePropertyChanged("recipientUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string senderUsername {
            get {
                return this.senderUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.senderUsernameField, value) != true)) {
                    this.senderUsernameField = value;
                    this.RaisePropertyChanged("senderUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                if ((this.timestampField.Equals(value) != true)) {
                    this.timestampField = value;
                    this.RaisePropertyChanged("timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SocialService.ISocialService", CallbackContract=typeof(GuessMyMessClient.SocialService.ISocialServiceCallback))]
    public interface ISocialService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/Connect")]
        void Connect(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/Connect")]
        System.Threading.Tasks.Task ConnectAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialService/GetFriendsList", ReplyAction="http://tempuri.org/ISocialService/GetFriendsListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/ISocialService/GetFriendsListStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        GuessMyMessClient.SocialService.FriendDto[] GetFriendsList(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialService/GetFriendsList", ReplyAction="http://tempuri.org/ISocialService/GetFriendsListResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.SocialService.FriendDto[]> GetFriendsListAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialService/GetFriendRequests", ReplyAction="http://tempuri.org/ISocialService/GetFriendRequestsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/ISocialService/GetFriendRequestsStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        GuessMyMessClient.SocialService.FriendRequestInfoDto[] GetFriendRequests(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialService/GetFriendRequests", ReplyAction="http://tempuri.org/ISocialService/GetFriendRequestsResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.SocialService.FriendRequestInfoDto[]> GetFriendRequestsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialService/SearchUsers", ReplyAction="http://tempuri.org/ISocialService/SearchUsersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/ISocialService/SearchUsersStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        GuessMyMessClient.SocialService.UserProfileDto[] SearchUsers(string searchUsername, string requesterUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialService/SearchUsers", ReplyAction="http://tempuri.org/ISocialService/SearchUsersResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.SocialService.UserProfileDto[]> SearchUsersAsync(string searchUsername, string requesterUsername);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/SendFriendRequest")]
        void SendFriendRequest(string requesterUsername, string targetUsername);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/SendFriendRequest")]
        System.Threading.Tasks.Task SendFriendRequestAsync(string requesterUsername, string targetUsername);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/RespondToFriendRequest")]
        void RespondToFriendRequest(string targetUsername, string requesterUsername, bool accepted);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/RespondToFriendRequest")]
        System.Threading.Tasks.Task RespondToFriendRequestAsync(string targetUsername, string requesterUsername, bool accepted);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/RemoveFriend")]
        void RemoveFriend(string username, string friendToRemove);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/RemoveFriend")]
        System.Threading.Tasks.Task RemoveFriendAsync(string username, string friendToRemove);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialService/InviteFriendToGameByEmail", ReplyAction="http://tempuri.org/ISocialService/InviteFriendToGameByEmailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/ISocialService/InviteFriendToGameByEmailStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        GuessMyMessClient.SocialService.OperationResultDto InviteFriendToGameByEmail(string fromUsername, string friendEmail, string matchCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialService/InviteFriendToGameByEmail", ReplyAction="http://tempuri.org/ISocialService/InviteFriendToGameByEmailResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.SocialService.OperationResultDto> InviteFriendToGameByEmailAsync(string fromUsername, string friendEmail, string matchCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/SendDirectMessage")]
        void SendDirectMessage(GuessMyMessClient.SocialService.DirectMessageDto message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/SendDirectMessage")]
        System.Threading.Tasks.Task SendDirectMessageAsync(GuessMyMessClient.SocialService.DirectMessageDto message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialService/GetConversations", ReplyAction="http://tempuri.org/ISocialService/GetConversationsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/ISocialService/GetConversationsStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        GuessMyMessClient.SocialService.FriendDto[] GetConversations(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialService/GetConversations", ReplyAction="http://tempuri.org/ISocialService/GetConversationsResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.SocialService.FriendDto[]> GetConversationsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialService/GetConversationHistory", ReplyAction="http://tempuri.org/ISocialService/GetConversationHistoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/ISocialService/GetConversationHistoryStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        GuessMyMessClient.SocialService.DirectMessageDto[] GetConversationHistory(string user1, string user2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialService/GetConversationHistory", ReplyAction="http://tempuri.org/ISocialService/GetConversationHistoryResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.SocialService.DirectMessageDto[]> GetConversationHistoryAsync(string user1, string user2);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/Disconnect")]
        void Disconnect(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/Disconnect")]
        System.Threading.Tasks.Task DisconnectAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISocialServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/NotifyFriendRequest")]
        void NotifyFriendRequest(string fromUsername);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/NotifyFriendResponse")]
        void NotifyFriendResponse(string fromUsername, bool accepted);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/NotifyFriendStatusChanged")]
        void NotifyFriendStatusChanged(string friendUsername, string status);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISocialService/NotifyMessageReceived")]
        void NotifyMessageReceived(GuessMyMessClient.SocialService.DirectMessageDto message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISocialServiceChannel : GuessMyMessClient.SocialService.ISocialService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SocialServiceClient : System.ServiceModel.DuplexClientBase<GuessMyMessClient.SocialService.ISocialService>, GuessMyMessClient.SocialService.ISocialService {
        
        public SocialServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public SocialServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public SocialServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SocialServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SocialServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Connect(string username) {
            base.Channel.Connect(username);
        }
        
        public System.Threading.Tasks.Task ConnectAsync(string username) {
            return base.Channel.ConnectAsync(username);
        }
        
        public GuessMyMessClient.SocialService.FriendDto[] GetFriendsList(string username) {
            return base.Channel.GetFriendsList(username);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.SocialService.FriendDto[]> GetFriendsListAsync(string username) {
            return base.Channel.GetFriendsListAsync(username);
        }
        
        public GuessMyMessClient.SocialService.FriendRequestInfoDto[] GetFriendRequests(string username) {
            return base.Channel.GetFriendRequests(username);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.SocialService.FriendRequestInfoDto[]> GetFriendRequestsAsync(string username) {
            return base.Channel.GetFriendRequestsAsync(username);
        }
        
        public GuessMyMessClient.SocialService.UserProfileDto[] SearchUsers(string searchUsername, string requesterUsername) {
            return base.Channel.SearchUsers(searchUsername, requesterUsername);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.SocialService.UserProfileDto[]> SearchUsersAsync(string searchUsername, string requesterUsername) {
            return base.Channel.SearchUsersAsync(searchUsername, requesterUsername);
        }
        
        public void SendFriendRequest(string requesterUsername, string targetUsername) {
            base.Channel.SendFriendRequest(requesterUsername, targetUsername);
        }
        
        public System.Threading.Tasks.Task SendFriendRequestAsync(string requesterUsername, string targetUsername) {
            return base.Channel.SendFriendRequestAsync(requesterUsername, targetUsername);
        }
        
        public void RespondToFriendRequest(string targetUsername, string requesterUsername, bool accepted) {
            base.Channel.RespondToFriendRequest(targetUsername, requesterUsername, accepted);
        }
        
        public System.Threading.Tasks.Task RespondToFriendRequestAsync(string targetUsername, string requesterUsername, bool accepted) {
            return base.Channel.RespondToFriendRequestAsync(targetUsername, requesterUsername, accepted);
        }
        
        public void RemoveFriend(string username, string friendToRemove) {
            base.Channel.RemoveFriend(username, friendToRemove);
        }
        
        public System.Threading.Tasks.Task RemoveFriendAsync(string username, string friendToRemove) {
            return base.Channel.RemoveFriendAsync(username, friendToRemove);
        }
        
        public GuessMyMessClient.SocialService.OperationResultDto InviteFriendToGameByEmail(string fromUsername, string friendEmail, string matchCode) {
            return base.Channel.InviteFriendToGameByEmail(fromUsername, friendEmail, matchCode);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.SocialService.OperationResultDto> InviteFriendToGameByEmailAsync(string fromUsername, string friendEmail, string matchCode) {
            return base.Channel.InviteFriendToGameByEmailAsync(fromUsername, friendEmail, matchCode);
        }
        
        public void SendDirectMessage(GuessMyMessClient.SocialService.DirectMessageDto message) {
            base.Channel.SendDirectMessage(message);
        }
        
        public System.Threading.Tasks.Task SendDirectMessageAsync(GuessMyMessClient.SocialService.DirectMessageDto message) {
            return base.Channel.SendDirectMessageAsync(message);
        }
        
        public GuessMyMessClient.SocialService.FriendDto[] GetConversations(string username) {
            return base.Channel.GetConversations(username);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.SocialService.FriendDto[]> GetConversationsAsync(string username) {
            return base.Channel.GetConversationsAsync(username);
        }
        
        public GuessMyMessClient.SocialService.DirectMessageDto[] GetConversationHistory(string user1, string user2) {
            return base.Channel.GetConversationHistory(user1, user2);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.SocialService.DirectMessageDto[]> GetConversationHistoryAsync(string user1, string user2) {
            return base.Channel.GetConversationHistoryAsync(user1, user2);
        }
        
        public void Disconnect(string username) {
            base.Channel.Disconnect(username);
        }
        
        public System.Threading.Tasks.Task DisconnectAsync(string username) {
            return base.Channel.DisconnectAsync(username);
        }
    }
}
