//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessMyMessClient.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GuessMyMessClient.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Owner.
        /// </summary>
        public static string answersPanelLbOwner {
            get {
                return ResourceManager.GetString("answersPanelLbOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Email.
        /// </summary>
        public static string changeEmailLbNewEmail {
            get {
                return ResourceManager.GetString("changeEmailLbNewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write your new email.
        /// </summary>
        public static string changeEmailLbWriteNewEmail {
            get {
                return ResourceManager.GetString("changeEmailLbWriteNewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Password.
        /// </summary>
        public static string changePswLbChangPsw {
            get {
                return ResourceManager.GetString("changePswLbChangPsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm your password.
        /// </summary>
        public static string changePswLbConfirmPsw {
            get {
                return ResourceManager.GetString("changePswLbConfirmPsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write your new password.
        /// </summary>
        public static string changePswLbWriteNewPsw {
            get {
                return ResourceManager.GetString("changePswLbWriteNewPsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification by Code.
        /// </summary>
        public static string changePswVerifyingLbVerifying {
            get {
                return ResourceManager.GetString("changePswVerifyingLbVerifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a word to draw.
        /// </summary>
        public static string chooseWordLbTitle {
            get {
                return ResourceManager.GetString("chooseWordLbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string configBtnEnglish {
            get {
                return ResourceManager.GetString("configBtnEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string configBtnSpanish {
            get {
                return ResourceManager.GetString("configBtnSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuration.
        /// </summary>
        public static string configLbConfiguration {
            get {
                return ResourceManager.GetString("configLbConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string configLbLanguage {
            get {
                return ResourceManager.GetString("configLbLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Music.
        /// </summary>
        public static string configLbMusic {
            get {
                return ResourceManager.GetString("configLbMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sound.
        /// </summary>
        public static string configLbSound {
            get {
                return ResourceManager.GetString("configLbSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sound Effects.
        /// </summary>
        public static string configLbSoundEffects {
            get {
                return ResourceManager.GetString("configLbSoundEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volume.
        /// </summary>
        public static string configLbVolume {
            get {
                return ResourceManager.GetString("configLbVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log Out.
        /// </summary>
        public static string configtBtnLogOut {
            get {
                return ResourceManager.GetString("configtBtnLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create.
        /// </summary>
        public static string createGameBtnCreate {
            get {
                return ResourceManager.GetString("createGameBtnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Private Match.
        /// </summary>
        public static string createGameBtnPrivateMatch {
            get {
                return ResourceManager.GetString("createGameBtnPrivateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Public Match.
        /// </summary>
        public static string createGameBtnPublicMatch {
            get {
                return ResourceManager.GetString("createGameBtnPublicMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Difficulty.
        /// </summary>
        public static string createGameCbDifficulty {
            get {
                return ResourceManager.GetString("createGameCbDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Easy.
        /// </summary>
        public static string createGameCbEasy {
            get {
                return ResourceManager.GetString("createGameCbEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hard.
        /// </summary>
        public static string createGameCbHard {
            get {
                return ResourceManager.GetString("createGameCbHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intermediate.
        /// </summary>
        public static string createGameCbIntermediate {
            get {
                return ResourceManager.GetString("createGameCbIntermediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Match Name.
        /// </summary>
        public static string createGameLbMatchName {
            get {
                return ResourceManager.GetString("createGameLbMatchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max. Players.
        /// </summary>
        public static string createGameLbMaxPlayers {
            get {
                return ResourceManager.GetString("createGameLbMaxPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rounds.
        /// </summary>
        public static string createGameLbRounds {
            get {
                return ResourceManager.GetString("createGameLbRounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Match Settings.
        /// </summary>
        public static string createGameLbSettings {
            get {
                return ResourceManager.GetString("createGameLbSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Circle.
        /// </summary>
        public static string drawingScreenBtnCircle {
            get {
                return ResourceManager.GetString("drawingScreenBtnCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eraser.
        /// </summary>
        public static string drawingScreenBtnEraser {
            get {
                return ResourceManager.GetString("drawingScreenBtnEraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pencil.
        /// </summary>
        public static string drawingScreenBtnPencil {
            get {
                return ResourceManager.GetString("drawingScreenBtnPencil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Square.
        /// </summary>
        public static string drawingScreenBtnSquare {
            get {
                return ResourceManager.GetString("drawingScreenBtnSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Triangle.
        /// </summary>
        public static string drawingScreenBtnTriangle {
            get {
                return ResourceManager.GetString("drawingScreenBtnTriangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thickness.
        /// </summary>
        public static string drawingScreenLbThickness {
            get {
                return ResourceManager.GetString("drawingScreenLbThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Draw!.
        /// </summary>
        public static string drawingScreenLbTitleDraw {
            get {
                return ResourceManager.GetString("drawingScreenLbTitleDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Word.
        /// </summary>
        public static string drawingScreenLbWord {
            get {
                return ResourceManager.GetString("drawingScreenLbWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Avatar.
        /// </summary>
        public static string editAvatarLbSelect {
            get {
                return ResourceManager.GetString("editAvatarLbSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Email.
        /// </summary>
        public static string editProfileBtnChangeEmail {
            get {
                return ResourceManager.GetString("editProfileBtnChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Password.
        /// </summary>
        public static string editProfileBtnChangePsw {
            get {
                return ResourceManager.GetString("editProfileBtnChangePsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Changes.
        /// </summary>
        public static string editProfileBtnSaveChanges {
            get {
                return ResourceManager.GetString("editProfileBtnSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My Profile.
        /// </summary>
        public static string editProfileLbMyProfile {
            get {
                return ResourceManager.GetString("editProfileLbMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat.
        /// </summary>
        public static string globalBtnChat {
            get {
                return ResourceManager.GetString("globalBtnChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string globalBtnClose {
            get {
                return ResourceManager.GetString("globalBtnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuration.
        /// </summary>
        public static string globalBtnConfiguration {
            get {
                return ResourceManager.GetString("globalBtnConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm.
        /// </summary>
        public static string globalBtnConfirm {
            get {
                return ResourceManager.GetString("globalBtnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Avatar.
        /// </summary>
        public static string globalBtnEditAvatar {
            get {
                return ResourceManager.GetString("globalBtnEditAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Profile.
        /// </summary>
        public static string globalBtnEditProfile {
            get {
                return ResourceManager.GetString("globalBtnEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join.
        /// </summary>
        public static string globalBtnJoin {
            get {
                return ResourceManager.GetString("globalBtnJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        public static string globalBtnLogIn {
            get {
                return ResourceManager.GetString("globalBtnLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimize.
        /// </summary>
        public static string globalBtnMinimize {
            get {
                return ResourceManager.GetString("globalBtnMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resize.
        /// </summary>
        public static string globalBtnResize {
            get {
                return ResourceManager.GetString("globalBtnResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Return.
        /// </summary>
        public static string globalBtnReturn {
            get {
                return ResourceManager.GetString("globalBtnReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string globalBtnSend {
            get {
                return ResourceManager.GetString("globalBtnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sing Up.
        /// </summary>
        public static string globalBtnSignUp {
            get {
                return ResourceManager.GetString("globalBtnSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Social.
        /// </summary>
        public static string globalBtnSocial {
            get {
                return ResourceManager.GetString("globalBtnSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify.
        /// </summary>
        public static string globalBtnVerify {
            get {
                return ResourceManager.GetString("globalBtnVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Female.
        /// </summary>
        public static string globalCmbFemale {
            get {
                return ResourceManager.GetString("globalCmbFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gender.
        /// </summary>
        public static string globalCmbGender {
            get {
                return ResourceManager.GetString("globalCmbGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Male.
        /// </summary>
        public static string globalCmbMale {
            get {
                return ResourceManager.GetString("globalCmbMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Non-Binary.
        /// </summary>
        public static string globalCmbNonBinary {
            get {
                return ResourceManager.GetString("globalCmbNonBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Changes Saved!.
        /// </summary>
        public static string globalLbChangesConfirmation {
            get {
                return ResourceManager.GetString("globalLbChangesConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Difficulty.
        /// </summary>
        public static string globalLbDifficulty {
            get {
                return ResourceManager.GetString("globalLbDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Easy.
        /// </summary>
        public static string globalLbEasy {
            get {
                return ResourceManager.GetString("globalLbEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string globalLbEmail {
            get {
                return ResourceManager.GetString("globalLbEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gender.
        /// </summary>
        public static string globalLbGender {
            get {
                return ResourceManager.GetString("globalLbGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hard.
        /// </summary>
        public static string globalLbHard {
            get {
                return ResourceManager.GetString("globalLbHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Host.
        /// </summary>
        public static string globalLbHost {
            get {
                return ResourceManager.GetString("globalLbHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intermediate.
        /// </summary>
        public static string globalLbIntermediate {
            get {
                return ResourceManager.GetString("globalLbIntermediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lastname.
        /// </summary>
        public static string globalLbLastName {
            get {
                return ResourceManager.GetString("globalLbLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Match Code.
        /// </summary>
        public static string globalLbMatchCode {
            get {
                return ResourceManager.GetString("globalLbMatchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string globalLbName {
            get {
                return ResourceManager.GetString("globalLbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players.
        /// </summary>
        public static string globalLbPlayers {
            get {
                return ResourceManager.GetString("globalLbPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write the verification code sent by email.
        /// </summary>
        public static string globalLbVerifyinText {
            get {
                return ResourceManager.GetString("globalLbVerifyinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string globalPwdPassword {
            get {
                return ResourceManager.GetString("globalPwdPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write a message.
        /// </summary>
        public static string globalTfPromtText {
            get {
                return ResourceManager.GetString("globalTfPromtText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string globalTxtEmail {
            get {
                return ResourceManager.GetString("globalTxtEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string globalTxtName {
            get {
                return ResourceManager.GetString("globalTxtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string globalTxtUsername {
            get {
                return ResourceManager.GetString("globalTxtUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guess the word.
        /// </summary>
        public static string guessScreenLbTitleGuessWord {
            get {
                return ResourceManager.GetString("guessScreenLbTitleGuessWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write the answer.
        /// </summary>
        public static string guessScreenTfPromptText {
            get {
                return ResourceManager.GetString("guessScreenTfPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Game.
        /// </summary>
        public static string lobbyBtnCreateGame {
            get {
                return ResourceManager.GetString("lobbyBtnCreateGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play.
        /// </summary>
        public static string lobbyBtnPlay {
            get {
                return ResourceManager.GetString("lobbyBtnPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a From.
        /// </summary>
        public static string lobbyChatLbFromMessage {
            get {
                return ResourceManager.GetString("lobbyChatLbFromMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send to.
        /// </summary>
        public static string lobbyChatLbSendTo {
            get {
                return ResourceManager.GetString("lobbyChatLbSendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        public static string logInLbLogIn {
            get {
                return ResourceManager.GetString("logInLbLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username or Email.
        /// </summary>
        public static string loginLbUsernameOrEmail {
            get {
                return ResourceManager.GetString("loginLbUsernameOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Private Matches.
        /// </summary>
        public static string playMenuBtnPrivateMatches {
            get {
                return ResourceManager.GetString("playMenuBtnPrivateMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Public Matches.
        /// </summary>
        public static string playMenuBtnPublicMatches {
            get {
                return ResourceManager.GetString("playMenuBtnPublicMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Available Matches.
        /// </summary>
        public static string playMenuLbAvailableMatches {
            get {
                return ResourceManager.GetString("playMenuLbAvailableMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the code of the match to join.
        /// </summary>
        public static string privateMatchesLbCodeMessage {
            get {
                return ResourceManager.GetString("privateMatchesLbCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        public static string signUpLbResgister {
            get {
                return ResourceManager.GetString("signUpLbResgister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Friend.
        /// </summary>
        public static string socialBtnAddFriend {
            get {
                return ResourceManager.GetString("socialBtnAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sent Invitation by Email.
        /// </summary>
        public static string socialBtnEmailInivite {
            get {
                return ResourceManager.GetString("socialBtnEmailInivite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string socialBtnSearch {
            get {
                return ResourceManager.GetString("socialBtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send Invite.
        /// </summary>
        public static string socialBtnSendInvite {
            get {
                return ResourceManager.GetString("socialBtnSendInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitation by Email.
        /// </summary>
        public static string socialLbEmailInvitation {
            get {
                return ResourceManager.GetString("socialLbEmailInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string socialLbFriends {
            get {
                return ResourceManager.GetString("socialLbFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requests.
        /// </summary>
        public static string socialLbRequests {
            get {
                return ResourceManager.GetString("socialLbRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string socialTfEmail {
            get {
                return ResourceManager.GetString("socialTfEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search Players.
        /// </summary>
        public static string socialTfSearchPlayers {
            get {
                return ResourceManager.GetString("socialTfSearchPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start.
        /// </summary>
        public static string waitingRoomBtnStart {
            get {
                return ResourceManager.GetString("waitingRoomBtnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The match starts in.
        /// </summary>
        public static string waitingRoomLbCountDown {
            get {
                return ResourceManager.GetString("waitingRoomLbCountDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Private.
        /// </summary>
        public static string waitingRoomLbMatchTypePrivate {
            get {
                return ResourceManager.GetString("waitingRoomLbMatchTypePrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Public.
        /// </summary>
        public static string waitingRoomLbMatchTypePublic {
            get {
                return ResourceManager.GetString("waitingRoomLbMatchTypePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue as guest.
        /// </summary>
        public static string welcomeBtnCotinueAsGuest {
            get {
                return ResourceManager.GetString("welcomeBtnCotinueAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start.
        /// </summary>
        public static string welcomeBtnStart {
            get {
                return ResourceManager.GetString("welcomeBtnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign up or log in to enjoy the full experience, or continue as a guest..
        /// </summary>
        public static string welcomeLbDescription {
            get {
                return ResourceManager.GetString("welcomeLbDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string winnersScreenBtnExit {
            get {
                return ResourceManager.GetString("winnersScreenBtnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Congratulations.
        /// </summary>
        public static string winnersScreenLbCongrats {
            get {
                return ResourceManager.GetString("winnersScreenLbCongrats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The match ended.
        /// </summary>
        public static string winnersScreenLbTitleEndMatch {
            get {
                return ResourceManager.GetString("winnersScreenLbTitleEndMatch", resourceCulture);
            }
        }
    }
}
