//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessMyMessClient.AuthService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class OperationResultDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserProfileDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class UserProfileDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvatarIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GenderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GuessMyMessClient.AuthService.SocialNetworkDto[] socialNetworksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvatarId {
            get {
                return this.AvatarIdField;
            }
            set {
                if ((this.AvatarIdField.Equals(value) != true)) {
                    this.AvatarIdField = value;
                    this.RaisePropertyChanged("AvatarId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GenderId {
            get {
                return this.GenderIdField;
            }
            set {
                if ((this.GenderIdField.Equals(value) != true)) {
                    this.GenderIdField = value;
                    this.RaisePropertyChanged("GenderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GuessMyMessClient.AuthService.SocialNetworkDto[] socialNetworks {
            get {
                return this.socialNetworksField;
            }
            set {
                if ((object.ReferenceEquals(this.socialNetworksField, value) != true)) {
                    this.socialNetworksField = value;
                    this.RaisePropertyChanged("socialNetworks");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SocialNetworkDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class SocialNetworkDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NetworkTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserLinkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NetworkType {
            get {
                return this.NetworkTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.NetworkTypeField, value) != true)) {
                    this.NetworkTypeField = value;
                    this.RaisePropertyChanged("NetworkType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserLink {
            get {
                return this.UserLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.UserLinkField, value) != true)) {
                    this.UserLinkField = value;
                    this.RaisePropertyChanged("UserLink");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthService.IAuthenticationService")]
    public interface IAuthenticationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/Login", ReplyAction="http://tempuri.org/IAuthenticationService/LoginResponse")]
        GuessMyMessClient.AuthService.OperationResultDto Login(string emailOrUsername, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/Login", ReplyAction="http://tempuri.org/IAuthenticationService/LoginResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.AuthService.OperationResultDto> LoginAsync(string emailOrUsername, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/Register", ReplyAction="http://tempuri.org/IAuthenticationService/RegisterResponse")]
        GuessMyMessClient.AuthService.OperationResultDto Register(GuessMyMessClient.AuthService.UserProfileDto userProfile, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/Register", ReplyAction="http://tempuri.org/IAuthenticationService/RegisterResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.AuthService.OperationResultDto> RegisterAsync(GuessMyMessClient.AuthService.UserProfileDto userProfile, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/VerifyAccount", ReplyAction="http://tempuri.org/IAuthenticationService/VerifyAccountResponse")]
        GuessMyMessClient.AuthService.OperationResultDto VerifyAccount(string email, string verificationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/VerifyAccount", ReplyAction="http://tempuri.org/IAuthenticationService/VerifyAccountResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.AuthService.OperationResultDto> VerifyAccountAsync(string email, string verificationCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAuthenticationService/LogOut")]
        void LogOut(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAuthenticationService/LogOut")]
        System.Threading.Tasks.Task LogOutAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/LoginAsGuest", ReplyAction="http://tempuri.org/IAuthenticationService/LoginAsGuestResponse")]
        GuessMyMessClient.AuthService.OperationResultDto LoginAsGuest(string username, string avatarPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/LoginAsGuest", ReplyAction="http://tempuri.org/IAuthenticationService/LoginAsGuestResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.AuthService.OperationResultDto> LoginAsGuestAsync(string username, string avatarPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/SendPasswordRecoveryCode", ReplyAction="http://tempuri.org/IAuthenticationService/SendPasswordRecoveryCodeResponse")]
        GuessMyMessClient.AuthService.OperationResultDto SendPasswordRecoveryCode(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/SendPasswordRecoveryCode", ReplyAction="http://tempuri.org/IAuthenticationService/SendPasswordRecoveryCodeResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.AuthService.OperationResultDto> SendPasswordRecoveryCodeAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/ResetPasswordWithCode", ReplyAction="http://tempuri.org/IAuthenticationService/ResetPasswordWithCodeResponse")]
        GuessMyMessClient.AuthService.OperationResultDto ResetPasswordWithCode(string email, string code, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/ResetPasswordWithCode", ReplyAction="http://tempuri.org/IAuthenticationService/ResetPasswordWithCodeResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.AuthService.OperationResultDto> ResetPasswordWithCodeAsync(string email, string code, string newPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthenticationServiceChannel : GuessMyMessClient.AuthService.IAuthenticationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticationServiceClient : System.ServiceModel.ClientBase<GuessMyMessClient.AuthService.IAuthenticationService>, GuessMyMessClient.AuthService.IAuthenticationService {
        
        public AuthenticationServiceClient() {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GuessMyMessClient.AuthService.OperationResultDto Login(string emailOrUsername, string password) {
            return base.Channel.Login(emailOrUsername, password);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.AuthService.OperationResultDto> LoginAsync(string emailOrUsername, string password) {
            return base.Channel.LoginAsync(emailOrUsername, password);
        }
        
        public GuessMyMessClient.AuthService.OperationResultDto Register(GuessMyMessClient.AuthService.UserProfileDto userProfile, string password) {
            return base.Channel.Register(userProfile, password);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.AuthService.OperationResultDto> RegisterAsync(GuessMyMessClient.AuthService.UserProfileDto userProfile, string password) {
            return base.Channel.RegisterAsync(userProfile, password);
        }
        
        public GuessMyMessClient.AuthService.OperationResultDto VerifyAccount(string email, string verificationCode) {
            return base.Channel.VerifyAccount(email, verificationCode);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.AuthService.OperationResultDto> VerifyAccountAsync(string email, string verificationCode) {
            return base.Channel.VerifyAccountAsync(email, verificationCode);
        }
        
        public void LogOut(string username) {
            base.Channel.LogOut(username);
        }
        
        public System.Threading.Tasks.Task LogOutAsync(string username) {
            return base.Channel.LogOutAsync(username);
        }
        
        public GuessMyMessClient.AuthService.OperationResultDto LoginAsGuest(string username, string avatarPath) {
            return base.Channel.LoginAsGuest(username, avatarPath);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.AuthService.OperationResultDto> LoginAsGuestAsync(string username, string avatarPath) {
            return base.Channel.LoginAsGuestAsync(username, avatarPath);
        }
        
        public GuessMyMessClient.AuthService.OperationResultDto SendPasswordRecoveryCode(string email) {
            return base.Channel.SendPasswordRecoveryCode(email);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.AuthService.OperationResultDto> SendPasswordRecoveryCodeAsync(string email) {
            return base.Channel.SendPasswordRecoveryCodeAsync(email);
        }
        
        public GuessMyMessClient.AuthService.OperationResultDto ResetPasswordWithCode(string email, string code, string newPassword) {
            return base.Channel.ResetPasswordWithCode(email, code, newPassword);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.AuthService.OperationResultDto> ResetPasswordWithCodeAsync(string email, string code, string newPassword) {
            return base.Channel.ResetPasswordWithCodeAsync(email, code, newPassword);
        }
    }
}
