//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessMyMessClient.AuthService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class OperationResultDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserProfileDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class UserProfileDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string avatarPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> genderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GuessMyMessClient.AuthService.SocialNetworkDto[] socialNetworksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string avatarPath {
            get {
                return this.avatarPathField;
            }
            set {
                if ((object.ReferenceEquals(this.avatarPathField, value) != true)) {
                    this.avatarPathField = value;
                    this.RaisePropertyChanged("avatarPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> genderId {
            get {
                return this.genderIdField;
            }
            set {
                if ((this.genderIdField.Equals(value) != true)) {
                    this.genderIdField = value;
                    this.RaisePropertyChanged("genderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GuessMyMessClient.AuthService.SocialNetworkDto[] socialNetworks {
            get {
                return this.socialNetworksField;
            }
            set {
                if ((object.ReferenceEquals(this.socialNetworksField, value) != true)) {
                    this.socialNetworksField = value;
                    this.RaisePropertyChanged("socialNetworks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SocialNetworkDto", Namespace="http://schemas.datacontract.org/2004/07/GuessMyMessServer.Contracts.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class SocialNetworkDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string networkTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userLinkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string networkType {
            get {
                return this.networkTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.networkTypeField, value) != true)) {
                    this.networkTypeField = value;
                    this.RaisePropertyChanged("networkType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userLink {
            get {
                return this.userLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.userLinkField, value) != true)) {
                    this.userLinkField = value;
                    this.RaisePropertyChanged("userLink");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthService.IAuthenticationService")]
    public interface IAuthenticationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/login", ReplyAction="http://tempuri.org/IAuthenticationService/loginResponse")]
        GuessMyMessClient.AuthService.OperationResultDto login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/login", ReplyAction="http://tempuri.org/IAuthenticationService/loginResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.AuthService.OperationResultDto> loginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/register", ReplyAction="http://tempuri.org/IAuthenticationService/registerResponse")]
        GuessMyMessClient.AuthService.OperationResultDto register(GuessMyMessClient.AuthService.UserProfileDto userProfile, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/register", ReplyAction="http://tempuri.org/IAuthenticationService/registerResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.AuthService.OperationResultDto> registerAsync(GuessMyMessClient.AuthService.UserProfileDto userProfile, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/verifyAccount", ReplyAction="http://tempuri.org/IAuthenticationService/verifyAccountResponse")]
        GuessMyMessClient.AuthService.OperationResultDto verifyAccount(string email, string verificationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/verifyAccount", ReplyAction="http://tempuri.org/IAuthenticationService/verifyAccountResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.AuthService.OperationResultDto> verifyAccountAsync(string email, string verificationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/loginAsGuest", ReplyAction="http://tempuri.org/IAuthenticationService/loginAsGuestResponse")]
        GuessMyMessClient.AuthService.OperationResultDto loginAsGuest(string username, string avatarPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/loginAsGuest", ReplyAction="http://tempuri.org/IAuthenticationService/loginAsGuestResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.AuthService.OperationResultDto> loginAsGuestAsync(string username, string avatarPath);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAuthenticationService/logOut")]
        void logOut(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAuthenticationService/logOut")]
        System.Threading.Tasks.Task logOutAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/sendPasswordRecoveryCode", ReplyAction="http://tempuri.org/IAuthenticationService/sendPasswordRecoveryCodeResponse")]
        GuessMyMessClient.AuthService.OperationResultDto sendPasswordRecoveryCode(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/sendPasswordRecoveryCode", ReplyAction="http://tempuri.org/IAuthenticationService/sendPasswordRecoveryCodeResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.AuthService.OperationResultDto> sendPasswordRecoveryCodeAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/resetPasswordWithCode", ReplyAction="http://tempuri.org/IAuthenticationService/resetPasswordWithCodeResponse")]
        GuessMyMessClient.AuthService.OperationResultDto resetPasswordWithCode(string email, string code, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/resetPasswordWithCode", ReplyAction="http://tempuri.org/IAuthenticationService/resetPasswordWithCodeResponse")]
        System.Threading.Tasks.Task<GuessMyMessClient.AuthService.OperationResultDto> resetPasswordWithCodeAsync(string email, string code, string newPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthenticationServiceChannel : GuessMyMessClient.AuthService.IAuthenticationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticationServiceClient : System.ServiceModel.ClientBase<GuessMyMessClient.AuthService.IAuthenticationService>, GuessMyMessClient.AuthService.IAuthenticationService {
        
        public AuthenticationServiceClient() {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GuessMyMessClient.AuthService.OperationResultDto login(string email, string password) {
            return base.Channel.login(email, password);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.AuthService.OperationResultDto> loginAsync(string email, string password) {
            return base.Channel.loginAsync(email, password);
        }
        
        public GuessMyMessClient.AuthService.OperationResultDto register(GuessMyMessClient.AuthService.UserProfileDto userProfile, string password) {
            return base.Channel.register(userProfile, password);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.AuthService.OperationResultDto> registerAsync(GuessMyMessClient.AuthService.UserProfileDto userProfile, string password) {
            return base.Channel.registerAsync(userProfile, password);
        }
        
        public GuessMyMessClient.AuthService.OperationResultDto verifyAccount(string email, string verificationCode) {
            return base.Channel.verifyAccount(email, verificationCode);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.AuthService.OperationResultDto> verifyAccountAsync(string email, string verificationCode) {
            return base.Channel.verifyAccountAsync(email, verificationCode);
        }
        
        public GuessMyMessClient.AuthService.OperationResultDto loginAsGuest(string username, string avatarPath) {
            return base.Channel.loginAsGuest(username, avatarPath);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.AuthService.OperationResultDto> loginAsGuestAsync(string username, string avatarPath) {
            return base.Channel.loginAsGuestAsync(username, avatarPath);
        }
        
        public void logOut(string username) {
            base.Channel.logOut(username);
        }
        
        public System.Threading.Tasks.Task logOutAsync(string username) {
            return base.Channel.logOutAsync(username);
        }
        
        public GuessMyMessClient.AuthService.OperationResultDto sendPasswordRecoveryCode(string email) {
            return base.Channel.sendPasswordRecoveryCode(email);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.AuthService.OperationResultDto> sendPasswordRecoveryCodeAsync(string email) {
            return base.Channel.sendPasswordRecoveryCodeAsync(email);
        }
        
        public GuessMyMessClient.AuthService.OperationResultDto resetPasswordWithCode(string email, string code, string newPassword) {
            return base.Channel.resetPasswordWithCode(email, code, newPassword);
        }
        
        public System.Threading.Tasks.Task<GuessMyMessClient.AuthService.OperationResultDto> resetPasswordWithCodeAsync(string email, string code, string newPassword) {
            return base.Channel.resetPasswordWithCodeAsync(email, code, newPassword);
        }
    }
}
